# render.yaml - Versão Corrigida com ipAllowList

services:
  # Serviço 1: Nosso banco de dados Redis.
  - type: redis
    name: redis-contador
    plan: free
    # A LINHA NOVA E IMPORTANTE ESTÁ AQUI:
    # Por segurança, a Render exige que você defina quem pode acessar o Redis.
    # Uma lista vazia '[]' significa que NENHUM IP externo pode se conectar,
    # mas outros serviços da sua conta Render (como nossa app) PODEM.
    # Esta é a configuração mais segura para nós.
    ipAllowList: []

  # Serviço 2: Nossa aplicação web C#.
  - type: web
    name: contador-de-cliques
    plan: free
    env: docker
    repo: https://github.com/victorbrandaao/ContadorDeCliques
    envVars:
      - key: REDIS_CONNECTION_STRING
        fromService:
          type: redis
          name: redis-contador
          property: connectionString
