# Nome do nosso workflow. Aparecerá na aba "Actions" do GitHub.
name: CI - Build and Push Docker Image

# Gatilho: este workflow vai rodar a cada 'push' na branch 'main'.
on:
  push:
    branches: ["main"]

# Permissões necessárias para o job poder publicar a imagem no GitHub Packages.
permissions:
  contents: read
  packages: write

# Tarefas a serem executadas.
jobs:
  build-and-push:
    # A máquina virtual que vai rodar nosso job. Usaremos a mais recente do Ubuntu.
    runs-on: ubuntu-latest

    # Os passos do nosso job.
    steps:
      # 1. Pega o nosso código do repositório para a máquina virtual.
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Faz o login no GitHub Container Registry (ghcr.io).
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # O GITHUB_TOKEN é um token especial gerado automaticamente pelo GitHub para cada job.
          # Ele já tem as permissões que definimos lá em cima.
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Constrói e "tagueia" a nossa imagem Docker.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # 'true' para realmente enviar a imagem para o registry.
          push: true
          # Cria duas "tags" (etiquetas) para a nossa imagem:
          # 1. 'latest', para ser fácil de pegar a última versão.
          # 2. Uma tag com o ID do commit, para termos uma versão única e rastreável.
          tags: |
          ghcr.io/victorbrandaao/contadordecliques:latest
          ghcr.io/victorbrandaao/contadordecliques:${{ github.sha }}
